# Generated by Django 4.2.23 on 2025-08-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefood', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
