# Generated by Django 4.2.23 on 2025-08-14 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thefood', '0004_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_store', to=settings.AUTH_USER_MODEL),
        ),
    ]
