# Generated by Django 4.2.23 on 2025-08-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefood', '0006_product_slug_product_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
