# Generated by Django 4.2.23 on 2025-10-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefood', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
