# Generated by Django 4.2.23 on 2026-02-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefood', '0014_storelocation_product_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerstore',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=255),
        ),
    ]
