# Generated by Django 4.2.23 on 2026-02-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefood', '0015_partnerstore_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstore',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=255),
        ),
    ]
