# Generated by Django 4.2.23 on 2026-02-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefood', '0017_fill_partnerstore_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstore',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
