# Generated by Django 4.2.23 on 2026-08-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefood', '0018_alter_partnerstore_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_subscription_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
