# Generated by Django 4.2.23 on 2026-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefood', '0019_product_is_subscription_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerstore',
            name='stripe_subscription_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
