# Generated by Django 4.2.23 on 2026-08-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefood', '0021_order_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thai_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
