# Generated by Django 4.2.23 on 2026-09-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thefood', '0022_category_thai_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sv', models.CharField(max_length=255)),
                ('name_th', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name_sv'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='thefood.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_items',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='thefood.ingredient'),
        ),
    ]
