# Generated by Django 4.2.23 on 2025-11-18 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('pillar', models.CharField(choices=[('Food', 'Food'), ('Game', 'Game'), ('Wellness', 'Wellness')], max_length=16)),
                ('language', models.CharField(choices=[('en', 'English'), ('sv', 'Swedish'), ('th', 'Thai')], default='en', max_length=4)),
                ('goal', models.CharField(choices=[('awareness', 'Awareness'), ('traffic', 'Traffic'), ('engagement', 'Engagement')], default='awareness', max_length=16)),
                ('keywords', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('email_body', models.TextField(blank=True)),
                ('social_caption', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('goal', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='studio.pillar')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(choices=[('en', 'English'), ('th', 'Thai'), ('sv', 'Swedish'), ('no', 'Norwegian')], default='en', max_length=2)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='studio.theme')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('th', 'Thai'), ('sv', 'Swedish'), ('no', 'Norwegian')], default='en', max_length=2)),
                ('tone', models.CharField(default='polite', max_length=100)),
                ('reply_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('canva_url', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_type', models.CharField(choices=[('pinterest_pin', 'Pinterest Pin'), ('fb_post', 'Facebook Post'), ('ig_post', 'Instagram Post'), ('yt_thumb', 'YouTube Thumbnail'), ('blog_hero', 'Blog Hero')], max_length=50)),
                ('thumbnail', models.ImageField(upload_to='studio/templates/thumbnails/')),
                ('ai_tool_key', models.CharField(help_text="Key for which AI tool / prompt config to use, e.g. 'campaign_pin'", max_length=100)),
                ('pillar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_templates', to='studio.pillar')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('image_prompt', models.TextField(blank=True)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_body', models.TextField(blank=True)),
                ('fb_text', models.TextField(blank=True)),
                ('ig_text', models.TextField(blank=True)),
                ('pin_title', models.CharField(blank=True, max_length=255)),
                ('pin_desc', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=255)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('DesignTemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaignPosts', to='studio.designtemplate')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='studio.campaign')),
                ('pillar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaignPost', to='studio.pillar')),
            ],
        ),
        migrations.CreateModel(
            name='AutoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('platforms', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('stm', 'stm'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], default='facebook', max_length=20)),
                ('topic', models.CharField(max_length=200)),
                ('keywords', models.TextField(blank=True)),
                ('tone', models.CharField(blank=True, default='friendly', max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('th', 'Thai'), ('sv', 'Swedish'), ('no', 'Norwegian')], default='en', max_length=2)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('image_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('CampaignPost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autoPosts', to='studio.campaignpost')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pillar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AutoPost', to='studio.pillar')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('stm', 'stm'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], default='pinterest', max_length=20)),
                ('script', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_desc', models.CharField(blank=True, max_length=160)),
                ('hashtags', models.CharField(blank=True, max_length=400)),
                ('image_prompt', models.TextField(blank=True)),
                ('canva_template_url', models.URLField(blank=True)),
                ('board', models.CharField(blank=True, max_length=120)),
                ('target_url', models.URLField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.topic')),
            ],
        ),
    ]
