# Generated by Django 4.2.23 on 2025-11-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('goal', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='studio.pillar')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(choices=[('en', 'English'), ('th', 'Thai'), ('sv', 'Swedish'), ('no', 'Norwegian')], default='en', max_length=2)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='studio.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('stm', 'stm'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], default='pinterest', max_length=20)),
                ('script', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_desc', models.CharField(blank=True, max_length=160)),
                ('hashtags', models.CharField(blank=True, max_length=400)),
                ('image_prompt', models.TextField(blank=True)),
                ('canva_template_url', models.URLField(blank=True)),
                ('board', models.CharField(blank=True, max_length=120)),
                ('target_url', models.URLField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.topic')),
            ],
        ),
    ]
