# Generated by Django 4.2.23 on 2025-12-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_designtemplate_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_post', models.OneToOneField(blank=True, help_text='Source AI post this public post was refined from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_post', to='studio.campaignpost')),
            ],
        ),
    ]
