# Generated by Django 4.2.23 on 2025-12-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_publicpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignpost',
            old_name='DesignTemplate',
            new_name='designTemplate',
        ),
    ]
