# Generated by Django 4.2.23 on 2025-12-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_rename_designtemplate_campaignpost_designtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='designtemplate',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='designtemplate',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
