# Generated by Django 4.2.23 on 2026-09-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_designtemplate_media_type_designtemplate_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignpost',
            name='blog_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaignpost',
            name='blog_excerpt',
            field=models.TextField(blank=True),
        ),
    ]
